apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loaddjer1471-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loaddjer1471-tenant-component
    app.kubernetes.io/part-of: loaddjer1471-tenant-app
  name: loaddjer1471-tenant-component
  namespace: loaddjer1471-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loaddjer1471-tenant-component
    weight: null
status: {}
